services:
  - type: web
    name: resume-chat-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
